language: node_js
node_js:
  - "10.15.0"

branches:
  only:
    - master

addons:
  chrome: stable

before_script:
  - yarn global add @angular/cli
 
cache:
  yarn: true
  directories:
    - node_modules

 
script:
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  local-dir: ./dist/
  on:
