language: node_js
node_js:
  - "10.15.0"

branches:
  only:
    - master

addons:
  chrome: stable

before_script:
  - yarn global add @angular/cli
 
cache:
  yarn: true
  directories:
    - node_modules


install:
  - npm install
 
script:
  - npm run lint
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
  - yarn build --base-href /learn-angular-testing/

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: false
  local_dir: dist/learn-angular-testing
  github_token: $GITHUB_TOKEN
  on:
    branch: master
